//! # sim_world - the voxel island
//!
//! A seeded **voxel world** (352 x 288 columns of 1 m, 56 layers, 22 x 18 chunks of 16 x 16 columns): terrain, cliffs
//! with overhangs, beaches, water, trees, bushes and village cottages are all blocks (`sim_core::blocks`). The island
//! design (lobed shoreline, 3-tier highland, pond + streams, coves, village clearing, paths, biomes) is generated by
//! `worldgen.rs` as a smooth design heightfield and voxelised by `voxel.rs`.
//!
//! Published through
//! * channel `vox.data` (`u16`, chunk-major block ids), `vox.chunks` (`u32` x 2 per chunk: version, highest layer + 1)
//!   and `vox.dirty` / `world.dirty` (chunk ids edited since the last step),
//! * derived read-only channels `world.height` (`f32`, top ground surface per column, cell-centre samples) and
//!   `world.biome` (`u8`), plus `flora` (`f32`, stride 8: decor only, kinds >= 32 and ferns),
//! * queries `world.info`, `world.blocks`, `world.block`, `world.raycast`, `world.ground`, `world.sweep`,
//! * commands `world.set_block|break_block|place_block|fill`, event `world.block_changed`,
//! * the [`HeightQuery`](sim_core::HeightQuery) and [`VoxelQuery`](sim_core::blocks::VoxelQuery) resources.

pub mod biome;
mod flora;
mod heightfield;
mod noise;
pub mod voxel;
mod worldgen;

pub use flora::{FLORA_STRIDE, MAX_FLORA, kind as flora_kind, kind_names};
pub use heightfield::{CELL, CELLS, CHUNK, HALF, Heightfield, SIZE, WorldTerrain};
pub use voxel::{Built, CH, CH_CELLS, NCHUNKS, NCX, NCZ, NX, NY, NZ, ORIGIN_X, ORIGIN_Z, SEA_Y, SharedWorld, TOTAL_CELLS, VoxelTerrain, VoxelWorld};
pub use worldgen::{Features, Generated, Pond, Stream, generate};

use bevy_app::{App, Plugin, Update};
use bevy_ecs::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};
use sim_core::blocks::{self, VoxelQuery};
use sim_core::math::Vec3;
use sim_core::{ChannelId, ChannelSpec, Channels, EventBus, EventKind, HeightQuery, SimAppExt, SimPublish, SimSet, SpawnPoints};
use std::sync::{Arc, RwLock};

/// `a` = new block id, `b` = previous block id, pos = block centre (world metres).
pub const BLOCK_CHANGED: EventKind = EventKind::world(0);

/// The generated world (resource).
#[derive(Resource)]
pub struct WorldData {
    pub world: SharedWorld,
    pub features: Arc<Features>,
    /// decor flora records (stride [`FLORA_STRIDE`])
    pub decor: Vec<f32>,
    pub seed: u32,
    pub caves: Vec<[f32; 6]>,
    pub cottages: Vec<[f32; 4]>,
    pub tree_count: usize,
}

/// Typed handles of this crate's channels.
#[derive(Resource, Clone, Copy)]
pub struct WorldChannels {
    pub height: ChannelId<f32>,
    pub biome: ChannelId<u8>,
    pub dirty: ChannelId<u32>,
    pub flora: ChannelId<f32>,
    pub vdata: ChannelId<u16>,
    pub vchunks: ChannelId<u32>,
    pub vdirty: ChannelId<u32>,
}

pub struct WorldPlugin;

/// Save section: the world is regenerated from the seed; only edited chunks (run-length encoded) are stored.
#[derive(Serialize, Deserialize)]
struct WorldSave {
    seed: u32,
    chunks: Vec<(u32, Vec<u16>)>,
}

impl Plugin for WorldPlugin {
    fn build(&self, app: &mut App) {
        let sim_seed = app.sim_seed();
        let seed = sim_seed.noise_seed("world");
        let generated = generate(seed);
        let flora = flora::scatter(&generated, sim_seed.noise_seed("flora"));
        let built = voxel::build(&generated, &flora, seed);
        let features = generated.features;
        let Built { world, decor, caves, cottages, tree_count } = built;
        let shared = SharedWorld(Arc::new(RwLock::new(world)));
        let sp = features.spawn;
        let spawn_y = shared.0.read().expect("voxel world lock").height_at(sp[0], sp[1]);

        app.insert_resource(HeightQuery::new(VoxelTerrain(shared.clone())));
        app.insert_resource(VoxelQuery::new(shared.clone()));
        app.insert_resource(SpawnPoints { player: Vec3::new(sp[0], spawn_y, sp[1]) });
        app.insert_resource(WorldData { world: shared, features: Arc::new(features), decor, seed, caves, cottages, tree_count });

        let columns = (NX * NZ) as u32;
        let channels = WorldChannels {
            height: app.register_channel::<f32>(
                ChannelSpec::flat::<f32>("world.height", columns).doc("DERIVED: top ground surface (m) per column, row-major z*nx+x, samples at block centres (world.info.sample = cell)"),
            ),
            biome: app.register_channel::<u8>(ChannelSpec::flat::<u8>("world.biome", columns).doc("DERIVED: biome id 0-11 per column (WORLD_CONTRACT.md)")),
            dirty: app.register_channel::<u32>(ChannelSpec::flat::<u32>("world.dirty", NCHUNKS as u32).doc("chunk indices edited this step (same as vox.dirty)")),
            flora: app.register_channel::<f32>(
                ChannelSpec::records::<f32>("flora", FLORA_STRIDE as u32, MAX_FLORA as u32).doc("DECOR only (kinds >= 32 + ferns): kind,x,y,z,yaw,scale,variant,state (static)"),
            ),
            vdata: app.register_channel::<u16>(
                ChannelSpec::flat::<u16>("vox.data", TOTAL_CELLS as u32)
                    .doc("block ids, chunk-major: ((cz*ncx+cx) * 16*16*ny) + ((lz*16+lx)*ny + layer); world y = layer - sea_y"),
            ),
            vchunks: app.register_channel::<u32>(ChannelSpec::records::<u32>("vox.chunks", 2, NCHUNKS as u32).doc("per chunk: mesh version, highest non-air layer + 1")),
            vdirty: app.register_channel::<u32>(ChannelSpec::flat::<u32>("vox.dirty", NCHUNKS as u32).doc("chunk ids edited since the last sim step (use vox.chunks versions to be safe)")),
        };
        app.insert_resource(channels);

        app.add_systems(Update, clear_dirty.in_set(SimSet::Env));
        app.add_systems(SimPublish, publish_world);

        app.register_event(BLOCK_CHANGED, "world.block_changed", "a = new block id, b = old block id, pos = block centre");
        app.register_query("world.info", |w: &World, _: Value| Ok(world_info(w)));
        app.register_query("world.blocks", |_: &World, _: Value| Ok(blocks::registry_json()));
        app.register_query("world.block", |w: &World, a: BlockPos| {
            let id = voxel_world(w).get(a.x, a.y, a.z);
            let d = blocks::def(id);
            Ok(json!({ "id": id, "name": d.name, "solid": blocks::is_solid(id), "liquid": blocks::is_liquid(id) }))
        });
        app.register_query("world.raycast", |w: &World, a: RayArgs| {
            let vw = voxel_world(w);
            let hit = blocks::raycast(&*vw, a.origin, a.dir, a.max.unwrap_or(64.0), a.liquids.unwrap_or(false));
            Ok(match hit {
                Some(h) => json!({ "hit": true, "pos": h.pos, "normal": h.normal, "id": h.id, "name": blocks::def(h.id).name, "dist": h.dist, "point": h.point }),
                None => json!({ "hit": false }),
            })
        });
        app.register_query("world.ground", |w: &World, a: GroundArgs| {
            let vw = voxel_world(w);
            Ok(json!({ "height": vw.height_at(a.x, a.z), "block_y": vw.ground_block_y(a.x.floor() as i32, a.z.floor() as i32), "biome": vw.biome_at(a.x, a.z) }))
        });
        app.register_query("world.sweep", |w: &World, a: SweepArgs| {
            let vw = voxel_world(w);
            let r = blocks::aabb_sweep(&*vw, a.min, a.size, a.delta);
            Ok(json!({ "pos": r.pos, "hit": r.hit }))
        });
        app.register_command("world.set_block", |w: &mut World, a: SetArgs| {
            let id = parse_block(a.id, &a.name)?;
            let (old, changed) = apply_edit(w, a.x, a.y, a.z, id)?;
            Ok(json!({ "old": old, "id": id, "changed": changed }))
        });
        app.register_command("world.break_block", |w: &mut World, a: BlockPos| {
            let old = voxel_world(w).get(a.x, a.y, a.z);
            if old == blocks::id::AIR {
                return Err("nothing to break there".to_string());
            }
            if blocks::is_liquid(old) {
                return Err("liquids cannot be broken".to_string());
            }
            if blocks::def(old).hardness < 0.0 {
                return Err("this block is unbreakable".to_string());
            }
            apply_edit(w, a.x, a.y, a.z, blocks::id::AIR)?;
            Ok(json!({ "old": old, "name": blocks::def(old).name, "drop": blocks::def(old).drop }))
        });
        app.register_command("world.place_block", |w: &mut World, a: SetArgs| {
            let id = parse_block(a.id, &a.name)?;
            if id == blocks::id::AIR {
                return Err("use world.break_block to remove blocks".to_string());
            }
            let old = voxel_world(w).get(a.x, a.y, a.z);
            if blocks::is_solid(old) {
                return Err("that space is occupied".to_string());
            }
            apply_edit(w, a.x, a.y, a.z, id)?;
            Ok(json!({ "old": old, "id": id }))
        });
        app.register_command("world.fill", |w: &mut World, a: FillArgs| {
            let id = parse_block(a.id, &a.name)?;
            let (x0, x1, y0, y1, z0, z1) = (a.x0.min(a.x1), a.x0.max(a.x1), a.y0.min(a.y1), a.y0.max(a.y1), a.z0.min(a.z1), a.z0.max(a.z1));
            let volume = i64::from(x1 - x0 + 1) * i64::from(y1 - y0 + 1) * i64::from(z1 - z0 + 1);
            if volume > 32_768 {
                return Err(format!("fill volume {volume} exceeds 32768 blocks"));
            }
            let mut changed = 0u32;
            for y in y0..=y1 {
                for z in z0..=z1 {
                    for x in x0..=x1 {
                        if let Ok((_, true)) = apply_edit(w, x, y, z, id) {
                            changed += 1;
                        }
                    }
                }
            }
            Ok(json!({ "changed": changed, "volume": volume }))
        });
        app.register_save_section(
            "world",
            2,
            |w: &World| {
                let data = w.resource::<WorldData>();
                let vw = data.world.0.read().expect("voxel world lock");
                let chunks = (0..NCHUNKS).filter(|&c| vw.edited[c]).map(|c| (c as u32, vw.encode_chunk(c))).collect();
                WorldSave { seed: data.seed, chunks }
            },
            |w: &mut World, s: WorldSave| {
                let (have, shared) = {
                    let d = w.resource::<WorldData>();
                    (d.seed, d.world.clone())
                };
                if s.seed != have {
                    return Err(format!("save was made on a different world (seed {} != {have})", s.seed));
                }
                {
                    let mut vw = shared.0.write().map_err(|_| "world lock poisoned".to_string())?;
                    for (c, rle) in &s.chunks {
                        vw.decode_chunk(*c as usize, rle)?;
                    }
                    vw.recompute_all();
                    vw.take_dirty();
                }
                // WorldData counts as changed => everything is republished after the load
                w.resource_mut::<WorldData>().set_changed();
                Ok(())
            },
        );
    }
}

fn voxel_world(w: &World) -> std::sync::RwLockReadGuard<'_, VoxelWorld> {
    w.resource::<WorldData>().world.0.read().expect("voxel world lock")
}

#[derive(Deserialize)]
struct BlockPos {
    x: i32,
    y: i32,
    z: i32,
}

#[derive(Deserialize)]
struct SetArgs {
    x: i32,
    y: i32,
    z: i32,
    id: Option<u16>,
    name: Option<String>,
}

#[derive(Deserialize)]
struct FillArgs {
    x0: i32,
    y0: i32,
    z0: i32,
    x1: i32,
    y1: i32,
    z1: i32,
    id: Option<u16>,
    name: Option<String>,
}

#[derive(Deserialize)]
struct RayArgs {
    origin: [f32; 3],
    dir: [f32; 3],
    max: Option<f32>,
    liquids: Option<bool>,
}

#[derive(Deserialize)]
struct GroundArgs {
    x: f32,
    z: f32,
}

#[derive(Deserialize)]
struct SweepArgs {
    min: [f32; 3],
    size: [f32; 3],
    delta: [f32; 3],
}

fn parse_block(id: Option<u16>, name: &Option<String>) -> Result<u16, String> {
    if let Some(i) = id {
        return if usize::from(i) < blocks::BLOCKS.len() { Ok(i) } else { Err(format!("unknown block id {i}")) };
    }
    if let Some(n) = name {
        return blocks::BLOCKS.iter().find(|d| d.name == n.as_str()).map(|d| d.id).ok_or_else(|| format!("unknown block '{n}'"));
    }
    Err("give `id` or `name`".to_string())
}

/// Applies one edit to the world and mirrors it into the channels (`vox.data`, `vox.chunks`, `world.height`, dirty lists)
/// and the event bus. Returns `(previous id, changed)`.
fn apply_edit(w: &mut World, x: i32, y: i32, z: i32, id: u16) -> Result<(u16, bool), String> {
    let ids = *w.resource::<WorldChannels>();
    let shared = w.resource::<WorldData>().world.clone();
    let (info, vers, surface) = {
        let mut vw = shared.0.write().map_err(|_| "world lock poisoned".to_string())?;
        let info = vw.edit(x, y, z, id)?;
        if !info.changed {
            return Ok((info.old, false));
        }
        let vers: Vec<(usize, u32, u8)> = info.chunks.iter().map(|&c| (c, vw.versions[c], vw.max_layer[c])).collect();
        let surface = vw.surface_m(info.column % NX, info.column / NX);
        vw.take_dirty();
        (info, vers, surface)
    };
    {
        let mut ch = w.resource_mut::<Channels>();
        ch.writer(ids.vdata).full_slice_mut()[info.cell] = id;
        {
            let mut cw = ch.writer(ids.vchunks);
            let s = cw.full_slice_mut();
            for (c, v, m) in &vers {
                s[c * 2] = *v;
                s[c * 2 + 1] = u32::from(*m);
            }
        }
        ch.writer(ids.height).full_slice_mut()[info.column] = surface;
        for (c, _, _) in &vers {
            for chan in [ids.dirty, ids.vdirty] {
                let mut dw = ch.writer(chan);
                let n = dw.len();
                let present = dw.full_slice_mut()[..n].contains(&(*c as u32));
                if !present {
                    dw.push(*c as u32);
                }
            }
        }
    }
    w.resource_mut::<EventBus>().emit(BLOCK_CHANGED, f32::from(id), f32::from(info.old), Vec3::new(x as f32 + 0.5, y as f32 + 0.5, z as f32 + 0.5), 0.0);
    Ok((info.old, true))
}

/// `world.dirty` / `vox.dirty` are per-step: empty unless a block was edited since the last step.
fn clear_dirty(mut channels: ResMut<Channels>, ids: Res<WorldChannels>) {
    channels.writer(ids.dirty).clear();
    channels.writer(ids.vdirty).clear();
}

/// Copies the world into the channels whenever `WorldData` changed (the first run after start-up / load always
/// publishes). Edits go through [`apply_edit`] and keep the channels current without a full republish.
fn publish_world(data: Res<WorldData>, ids: Res<WorldChannels>, mut channels: ResMut<Channels>) {
    if !data.is_changed() {
        return;
    }
    let vw = data.world.0.read().expect("voxel world lock");
    channels.writer(ids.vdata).replace_with(&vw.blocks);
    let mut table = Vec::with_capacity(NCHUNKS * 2);
    for c in 0..NCHUNKS {
        table.push(vw.versions[c]);
        table.push(u32::from(vw.max_layer[c]));
    }
    channels.writer(ids.vchunks).replace_with(&table);
    let mut heights = vec![0.0f32; NX * NZ];
    for iz in 0..NZ {
        for ix in 0..NX {
            heights[iz * NX + ix] = vw.surface_m(ix, iz);
        }
    }
    channels.writer(ids.height).replace_with(&heights);
    channels.writer(ids.biome).replace_with(&vw.biome);
    channels.writer(ids.flora).replace_with(&data.decor);
    for bump in [ids.height] {
        channels.bump_version(bump);
    }
    channels.bump_version(ids.biome);
    channels.bump_version(ids.flora);
    channels.bump_version(ids.vdata);
    channels.bump_version(ids.vchunks);
}

fn world_info(w: &World) -> Value {
    let data = w.resource::<WorldData>();
    let vw = data.world.0.read().expect("voxel world lock");
    let f = &data.features;
    let spawn = w.resource::<SpawnPoints>().player;
    let ids = w.resource::<WorldChannels>();
    let mut habitats = Map::new();
    for (id, circles) in &f.habitats {
        habitats.insert(biome::name(*id).to_string(), json!(circles));
    }
    let streams: Vec<Value> = f.streams.iter().map(|s| json!({ "pts": s.pts })).collect();
    let (mut lo, mut hi) = (f32::MAX, f32::MIN);
    for iz in (0..NZ).step_by(2) {
        for ix in (0..NX).step_by(2) {
            let h = vw.surface_m(ix, iz);
            lo = lo.min(h);
            hi = hi.max(h);
        }
    }
    let (ox, oz) = (ORIGIN_X as f32, ORIGIN_Z as f32);
    json!({
        // derived grid: one sample per block column, taken at the block centre ("cell" sampling)
        "size_x": NX, "size_z": NZ, "nx": NX, "nz": NZ, "cell": 1.0,
        "origin_x": ORIGIN_X, "origin_z": ORIGIN_Z, "sample": "cell",
        "sea_level": 0.0,
        "chunk": CH,
        "min_height": lo, "max_height": hi,
        "seed": data.seed,
        "spawn": { "player": f.spawn, "village": f.village, "x": spawn.x, "y": spawn.y, "z": spawn.z },
        "habitats": Value::Object(habitats),
        "bounds": { "min_x": ox + 4.0, "min_z": oz + 4.0, "max_x": ox + NX as f32 - 4.0, "max_z": oz + NZ as f32 - 4.0 },
        "biomes": biome::NAMES,
        "flora_kinds": kind_names(),
        "flora_count": data.decor.len() / FLORA_STRIDE,
        "water": {
            "sea": 0.0,
            "pond": { "x": f.pond.x, "z": f.pond.z, "rx": f.pond.rx, "rz": f.pond.rz, "rot": f.pond.rot, "level": f.pond.level },
            "streams": streams,
        },
        "village": { "x": f.village[0], "z": f.village[1], "r": f.village_r, "h": f.village_h },
        "paths": f.paths,
        "islets": f.islets,
        "highland": f.highland,
        "vox": {
            "nx": NX, "ny": NY, "nz": NZ, "chunk": CH, "ncx": NCX, "ncz": NCZ, "chunks": NCHUNKS,
            "cells_per_chunk": CH_CELLS, "origin": [ORIGIN_X, -SEA_Y, ORIGIN_Z], "sea_y": SEA_Y,
            "layout": "chunk-major, column-major inside a chunk (layer fastest): ((cz*ncx+cx)*cells_per_chunk) + ((lz*chunk+lx)*ny + layer)",
            "caves": data.caves, "cottages": data.cottages, "trees": data.tree_count,
        },
        "version": w.resource::<Channels>().version(ids.height),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use sim_core::Sim;
    use std::collections::{HashMap, VecDeque};
    use std::sync::{Mutex, OnceLock};

    fn sim(seed: u32) -> Sim {
        Sim::build(seed, |app| {
            app.add_plugins(WorldPlugin);
        })
    }

    /// Generated worlds are expensive in debug builds: share them between tests.
    fn shared(seed: u32) -> &'static Generated {
        static CACHE: OnceLock<Mutex<HashMap<u32, &'static Generated>>> = OnceLock::new();
        let mut map = CACHE.get_or_init(|| Mutex::new(HashMap::new())).lock().unwrap();
        *map.entry(seed).or_insert_with(|| Box::leak(Box::new(generate(seed))))
    }

    fn shared_built(seed: u32) -> &'static Built {
        static CACHE: OnceLock<Mutex<HashMap<u32, &'static Built>>> = OnceLock::new();
        let mut map = CACHE.get_or_init(|| Mutex::new(HashMap::new())).lock().unwrap();
        *map.entry(seed).or_insert_with(|| {
            let g = shared(seed);
            let flora = flora::scatter(g, 42);
            Box::leak(Box::new(voxel::build(g, &flora, seed)))
        })
    }

    fn count_biomes(hf: &Heightfield) -> [usize; biome::COUNT] {
        let mut c = [0usize; biome::COUNT];
        for &b in &hf.biomes {
            c[usize::from(b)] += 1;
        }
        c
    }

    fn json_of(s: &str) -> Value {
        serde_json::from_str(s).unwrap()
    }

    #[test]
    fn publishes_voxel_channels_and_info_at_startup() {
        let s = sim(5);
        let d = json_of(&s.channel_info_json("vox.data"));
        assert_eq!((d["len"].as_u64().unwrap() as usize, d["kind"].as_str().unwrap()), (TOTAL_CELLS, "u16"));
        let c = json_of(&s.channel_info_json("vox.chunks"));
        assert_eq!((c["len"].as_u64().unwrap() as usize, c["stride"].as_u64().unwrap()), (NCHUNKS * 2, 2));
        let h = json_of(&s.channel_info_json("world.height"));
        assert_eq!(h["len"].as_u64().unwrap() as usize, NX * NZ);
        let b = json_of(&s.channel_info_json("world.biome"));
        assert_eq!((b["len"].as_u64().unwrap() as usize, b["kind"].as_str().unwrap()), (NX * NZ, "u8"));
        let f = json_of(&s.channel_info_json("flora"));
        assert_eq!(f["stride"], 8);
        assert!(f["len"].as_u64().unwrap() >= 800, "decor flora: {}", f["len"]);
        for name in ["world.dirty", "vox.dirty"] {
            assert_eq!(json_of(&s.channel_info_json(name))["len"], 0, "{name}");
        }
        let info = json_of(&s.query("world.info", ""));
        for key in ["size_x", "size_z", "cell", "origin_x", "origin_z", "sea_level", "chunk", "spawn", "habitats", "bounds", "biomes", "water", "flora_kinds", "vox", "sample"] {
            assert!(info.get(key).is_some(), "world.info lacks '{key}'");
        }
        assert_eq!((info["size_x"].as_u64().unwrap(), info["size_z"].as_u64().unwrap(), info["cell"].as_f64().unwrap()), (352, 288, 1.0));
        assert_eq!(info["vox"]["ny"], NY);
        assert_eq!(info["vox"]["origin"][1], -SEA_Y);
        assert_eq!(info["biomes"].as_array().unwrap().len(), 12);
        assert_eq!(info["flora_kinds"][0], "oak_puff");
        let reg = json_of(&s.query("world.blocks", ""));
        assert_eq!(reg["blocks"].as_array().unwrap().len(), blocks::BLOCKS.len());
    }

    #[test]
    fn channels_mirror_the_world_and_height_query_walks_the_top() {
        let s = sim(11);
        let ch = s.world().resource::<Channels>();
        let ids = s.world().resource::<WorldChannels>();
        let data = ch.slice(ids.vdata);
        let heights = ch.slice(ids.height);
        let q = s.world().resource::<HeightQuery>();
        let vw = voxel_world(s.world());
        assert_eq!(data, &vw.blocks[..]);
        for &(ix, iz) in &[(10usize, 10usize), (176, 144), (300, 100), (351, 287), (120, 200)] {
            let (x, z) = ((ORIGIN_X + ix as i32) as f32 + 0.5, (ORIGIN_Z + iz as i32) as f32 + 0.5);
            assert_eq!(heights[iz * NX + ix], q.height(x, z), "column ({ix},{iz})");
            assert_eq!(heights[iz * NX + ix], vw.surface_m(ix, iz));
        }
        let spawn = s.world().resource::<SpawnPoints>().player;
        assert!(q.height(spawn.x, spawn.z) >= 1.0 && !q.is_water(spawn.x, spawn.z), "spawn y {}", spawn.y);
        assert!(q.is_water(ORIGIN_X as f32 + 10.0, ORIGIN_Z as f32 + 10.0));
        assert_eq!(q.sea_level(), 0.0);
        assert!(q.contains(spawn.x, spawn.z) && !q.contains(500.0, 0.0));
    }

    #[test]
    fn same_seed_same_world_different_seed_different_world() {
        assert_eq!(sim(7).digest(), sim(7).digest());
        assert_ne!(sim(7).digest(), sim(8).digest());
    }

    #[test]
    fn voxel_generation_is_deterministic_and_timed() {
        let g = shared(1);
        let flora = flora::scatter(g, 42);
        let t = std::time::Instant::now();
        let a = voxel::build(g, &flora, 1);
        let secs = t.elapsed().as_secs_f32();
        eprintln!("voxel::build(1): {secs:.2} s (native test profile), {} trees, {} decor, caves {:?}", a.tree_count, a.decor.len() / 8, a.caves.len());
        let b = shared_built(1);
        assert_eq!(a.world.blocks, b.world.blocks);
        assert_eq!(a.decor, b.decor);
        assert_ne!(a.world.blocks, shared_built(2).world.blocks);
        assert!(secs < 20.0);
    }

    #[test]
    fn world_rules_water_trees_spawn_and_borders() {
        for seed in [1u32, 2] {
            let b = shared_built(seed);
            let vw = &b.world;
            let g = shared(seed);
            // sea fill: every column whose ground is below sea level is water up to the surface layer
            let mut water_cells = 0usize;
            for iz in 0..NZ {
                for ix in 0..NX {
                    let top = vw.top[iz * NX + ix];
                    assert!(top >= 1, "seed {seed}: column ({ix},{iz}) has no ground");
                    if i32::from(top) + 1 - SEA_Y < 0 {
                        for l in (top as usize + 1)..SEA_Y as usize {
                            assert_eq!(vw.blocks[VoxelWorld::cell(ix, l, iz)], blocks::id::WATER, "seed {seed}: sea gap at ({ix},{l},{iz})");
                        }
                    }
                    // water is supported: the cell below water is water or solid; the world border is sea floor
                    let base = VoxelWorld::column_base(ix, iz);
                    for l in 1..NY {
                        if vw.blocks[base + l] == blocks::id::WATER {
                            water_cells += 1;
                            let below = vw.blocks[base + l - 1];
                            assert!(below == blocks::id::WATER || blocks::is_solid(below), "seed {seed}: floating water at ({ix},{l},{iz})");
                        }
                    }
                    if ix == 0 || iz == 0 || ix == NX - 1 || iz == NZ - 1 {
                        assert!(i32::from(top) + 1 - SEA_Y < -3, "seed {seed}: land touches the world border at ({ix},{iz})");
                    }
                }
            }
            assert!(water_cells > 100_000, "seed {seed}: only {water_cells} water cells");
            // inland water exists (pond + streams)
            let inland = (0..NX * NZ).filter(|&c| vw.top[c] as i32 + 1 - SEA_Y >= 1 && (1..NY).any(|l| vw.blocks[VoxelWorld::column_base(c % NX, c / NX) + l] == blocks::id::WATER)).count();
            assert!(inland > 300, "seed {seed}: inland water columns {inland}");
            // spawn
            let sp = g.features.spawn;
            let (sx, sz) = (sp[0].floor() as i32, sp[1].floor() as i32);
            let gy = vw.ground_block_y(sx, sz).expect("spawn column");
            assert!(gy >= 1, "seed {seed}: spawn ground {gy}");
            assert!(!blocks::is_solid(vw.get(sx, gy + 1, sz)) && !blocks::is_solid(vw.get(sx, gy + 2, sz)) && !blocks::is_liquid(vw.get(sx, gy + 1, sz)), "seed {seed}: spawn is blocked");
            // no floating trees: every vegetation block is face-connected to ground through vegetation
            let mut seen = vec![false; TOTAL_CELLS];
            let mut queue: VecDeque<(usize, usize, usize)> = VecDeque::new();
            let mut plants = 0usize;
            for iz in 0..NZ {
                for ix in 0..NX {
                    let base = VoxelWorld::column_base(ix, iz);
                    for l in 1..NY {
                        let id = vw.blocks[base + l];
                        if blocks::def(id).flags & blocks::flag::PLANT == 0 {
                            continue;
                        }
                        plants += 1;
                        let below = vw.blocks[base + l - 1];
                        if blocks::is_ground(below) && !seen[base + l] {
                            seen[base + l] = true;
                            queue.push_back((ix, l, iz));
                        }
                    }
                }
            }
            while let Some((x, y, z)) = queue.pop_front() {
                for (dx, dy, dz) in [(1i32, 0i32, 0i32), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)] {
                    let (a, l, c) = (x as i32 + dx, y as i32 + dy, z as i32 + dz);
                    if a < 0 || c < 0 || l < 1 || a >= NX as i32 || c >= NZ as i32 || l >= NY as i32 {
                        continue;
                    }
                    let cell = VoxelWorld::cell(a as usize, l as usize, c as usize);
                    if !seen[cell] && blocks::def(vw.blocks[cell]).flags & blocks::flag::PLANT != 0 {
                        seen[cell] = true;
                        queue.push_back((a as usize, l as usize, c as usize));
                    }
                }
            }
            let floating = (0..NX * NZ).flat_map(|c| (1..NY).map(move |l| (c, l))).filter(|&(c, l)| {
                let cell = VoxelWorld::column_base(c % NX, c / NX) + l;
                blocks::def(vw.blocks[cell]).flags & blocks::flag::PLANT != 0 && !seen[cell]
            });
            assert_eq!(floating.count(), 0, "seed {seed}: floating vegetation blocks");
            assert!(plants > 8_000 && b.tree_count > 250, "seed {seed}: {plants} plant blocks, {} trees", b.tree_count);
            // no 1-block spikes on land (a column higher than all four neighbours by exactly 1) outside villages / trees
            assert!(b.cottages.len() >= 2, "seed {seed}: cottages {}", b.cottages.len());
        }
    }

    #[test]
    fn edit_pipeline_set_break_place_raycast_and_save() {
        let mut s = sim(5);
        let sp = s.world().resource::<SpawnPoints>().player;
        let (x, z) = (sp.x.floor() as i32, sp.z.floor() as i32);
        let gy = voxel_world(s.world()).ground_block_y(x, z).unwrap();
        let ids = *s.world().resource::<WorldChannels>();
        let (ix, iz) = ((x - ORIGIN_X) as usize, (z - ORIGIN_Z) as usize);
        let chunk = voxel::chunk_of(ix, iz);
        let ver0 = s.world().resource::<Channels>().slice(ids.vchunks)[chunk * 2];
        let h0 = s.world().resource::<HeightQuery>().height(sp.x, sp.z);

        // break the ground block
        let r = json_of(&s.command("world.break_block", &format!(r#"{{"x":{x},"y":{gy},"z":{z}}}"#)));
        assert!(r.get("error").is_none(), "{r}");
        assert_eq!(json_of(&s.query("world.block", &format!(r#"{{"x":{x},"y":{gy},"z":{z}}}"#)))["id"], 0);
        let ch = s.world().resource::<Channels>();
        assert!(ch.slice(ids.vchunks)[chunk * 2] > ver0, "chunk version must bump");
        assert_eq!(ch.slice(ids.vdata)[VoxelWorld::cell(ix, (gy + SEA_Y) as usize, iz)], 0, "channel mirrors the edit");
        assert!(ch.slice(ids.vdirty).contains(&(chunk as u32)) && ch.slice(ids.dirty).contains(&(chunk as u32)));
        assert!(s.world().resource::<HeightQuery>().height(sp.x, sp.z) < h0, "ground gets lower");
        assert!(s.world().resource::<EventBus>().len() >= 1, "block_changed event");
        // raycast from above hits the new top (the block below the hole) with a +y normal
        let ray = json_of(&s.query("world.raycast", &format!(r#"{{"origin":[{},{},{}],"dir":[0,-1,0],"max":60}}"#, x as f32 + 0.5, gy as f32 + 10.0, z as f32 + 0.5)));
        assert_eq!((ray["hit"].as_bool(), ray["pos"][1].as_i64(), ray["normal"][1].as_i64()), (Some(true), Some(i64::from(gy) - 1), Some(1)), "{ray}");
        // place something back, by name
        let p = json_of(&s.command("world.place_block", &format!(r#"{{"x":{x},"y":{gy},"z":{z},"name":"planks"}}"#)));
        assert!(p.get("error").is_none(), "{p}");
        assert_eq!(json_of(&s.query("world.block", &format!(r#"{{"x":{x},"y":{gy},"z":{z}}}"#)))["name"], "planks");
        let again = json_of(&s.command("world.place_block", &format!(r#"{{"x":{x},"y":{gy},"z":{z},"name":"planks"}}"#)));
        assert!(again.get("error").is_some(), "occupied");
        assert!(json_of(&s.command("world.break_block", r#"{"x":0,"y":-14,"z":0}"#)).get("error").is_some(), "bedrock layer / water");
        // chunk border edits also bump the neighbour
        let bx = ORIGIN_X + (16 * 10) as i32; // lx == 0 of chunk column 10
        let bz = ORIGIN_Z + 40;
        let v_left = s.world().resource::<Channels>().slice(ids.vchunks)[voxel::chunk_of(16 * 10 - 1, 40) * 2];
        let top = voxel_world(s.world()).ground_block_y(bx, bz).unwrap();
        s.command("world.set_block", &format!(r#"{{"x":{bx},"y":{},"z":{bz},"name":"stone"}}"#, top + 1));
        assert!(s.world().resource::<Channels>().slice(ids.vchunks)[voxel::chunk_of(16 * 10 - 1, 40) * 2] > v_left, "neighbour chunk remeshes");
        // save: only edited chunks, round trip into a fresh sim
        let bytes = s.save().unwrap();
        assert!(bytes.len() < 200_000, "save is chunk-diff sized: {} bytes", bytes.len());
        let file = sim_core::SaveFile::decode(&bytes).unwrap();
        let mut fresh = sim(5);
        fresh.apply_save(&file).unwrap();
        assert_eq!(json_of(&fresh.query("world.block", &format!(r#"{{"x":{x},"y":{gy},"z":{z}}}"#)))["name"], "planks");
        let ids2 = *fresh.world().resource::<WorldChannels>();
        fresh.step_once();
        assert_eq!(fresh.world().resource::<Channels>().slice(ids2.vdata), s.world().resource::<Channels>().slice(ids.vdata));
        // fill
        let f = json_of(&s.command("world.fill", &format!(r#"{{"x0":{x},"y0":{},"z0":{z},"x1":{},"y1":{},"z1":{},"name":"cobble"}}"#, gy + 2, x + 2, gy + 3, z + 2)));
        assert_eq!(f["changed"], 18, "{f}");
    }

    #[test]
    fn collision_helpers_work_on_the_island() {
        let s = sim(5);
        let q = s.world().resource::<VoxelQuery>();
        let sp = s.world().resource::<SpawnPoints>().player;
        let (x, z) = (sp.x.floor() as i32, sp.z.floor() as i32);
        let gy = q.ground_y(x, z, 50, -14).unwrap();
        assert!(q.is_solid(x, gy, z) && !q.is_solid(x, gy + 1, z));
        let hit = q.raycast([sp.x, gy as f32 + 20.0, sp.z], [0.0, -1.0, 0.0], 80.0, false).unwrap();
        assert_eq!(hit.pos, [x, gy, z]);
        // a standing box dropped from 6 m lands exactly on the surface
        let r = q.aabb_sweep([x as f32 + 0.2, gy as f32 + 7.0, z as f32 + 0.2], [0.6, 1.8, 0.6], [0.0, -12.0, 0.0]);
        assert!(r.hit[1] && (r.pos[1] - (gy as f32 + 1.0)).abs() < 0.01, "{r:?}");
    }

    #[test]
    fn world_save_section_checks_the_seed() {
        let a = sim(5);
        let bytes = a.save().unwrap();
        let file = sim_core::SaveFile::decode(&bytes).unwrap();
        let mut same = sim(5);
        same.apply_save(&file).unwrap();
        let mut other = sim(6);
        let e = other.apply_save(&file).unwrap_err();
        assert!(e.contains("different world"), "{e}");
    }

    // ---- the smooth design layer (heightfield) keeps its own tests -------------------------------

    #[test]
    fn island_has_the_designed_topography() {
        for seed in [1u32, 2, 3] {
            let g = shared(seed);
            let hf = &g.field;
            let c = count_biomes(hf);
            for id in 0..=10 {
                assert!(c[id] > 150, "seed {seed}: biome {} ({}) has only {} cells", id, biome::NAMES[id], c[id]);
            }
            assert_eq!(c[usize::from(biome::SNOW)], 0);
            let land: usize = (2..=10).map(|i| c[i]).sum();
            let frac = land as f32 / (SIZE * SIZE) as f32;
            assert!((0.12..0.45).contains(&frac), "seed {seed}: land fraction {frac}");
            assert!(hf.max_height > 13.0 && hf.max_height < 32.0, "seed {seed}: max {}", hf.max_height);
            assert!(hf.min_height > -14.5, "seed {seed}: min {}", hf.min_height);
            let (v, p) = (g.features.village, &g.features.pond);
            assert!(hf.sample(p.x, p.z) < p.level - 0.5, "seed {seed}: pond basin");
            assert!(p.level > 1.0 && p.level < 9.0, "seed {seed}: pond level {}", p.level);
            // the voxel window (x -160..192, z -136..152) contains the village, pond, spawn and the highland
            let inside = |x: f32, z: f32| x > -150.0 && x < 182.0 && z > -126.0 && z < 142.0;
            assert!(inside(v[0], v[1]) && inside(p.x, p.z) && inside(g.features.spawn[0], g.features.spawn[1]), "seed {seed}: features outside the voxel window");
            assert!(inside(g.features.highland[0], g.features.highland[1]), "seed {seed}: highland outside the voxel window");
        }
    }

    #[test]
    fn stream_runs_from_the_highland_foot_through_the_pond_to_the_sea() {
        for seed in [1u32, 2, 3] {
            let g = shared(seed);
            let hf = &g.field;
            let s = &g.features.streams;
            assert_eq!(s.len(), 2);
            for st in s {
                assert!(st.pts.len() > 12);
                for w in st.pts.windows(2) {
                    assert!(w[1][3] <= w[0][3] + 1e-4, "seed {seed}: stream level rises {} -> {}", w[0][3], w[1][3]);
                }
            }
            let out = &s[1].pts;
            let last = out.last().unwrap();
            assert!(last[3] <= 0.05, "seed {seed}: stream mouth level {}", last[3]);
            assert!(hf.sample(last[0], last[1]) < 0.4, "seed {seed}: stream must end in the sea, ground {}", hf.sample(last[0], last[1]));
            let c = count_biomes(hf);
            assert!(c[usize::from(biome::POND_BANK)] > 800, "seed {seed}: pond/stream bank cells {}", c[8]);
        }
    }

    #[test]
    fn flora_follows_the_contract_rules() {
        for seed in [1u32, 2] {
            let g = shared(seed);
            let hf = &g.field;
            let flora = flora::scatter(g, 42);
            assert_eq!(flora.len() % FLORA_STRIDE, 0);
            let n = flora.len() / FLORA_STRIDE;
            assert!((2200..MAX_FLORA * 8 / 10).contains(&n), "seed {seed}: {n} instances");
            let names = kind_names();
            let mut per_kind = [0usize; 128];
            for r in flora.chunks_exact(FLORA_STRIDE) {
                let k = r[0] as usize;
                assert!(k < 128 && !names[k].is_empty(), "unknown kind {k}");
                per_kind[k] += 1;
                let (x, y, z) = (r[1], r[2], r[3]);
                assert!(r[5] > 0.0 && (0.0..=255.0).contains(&r[6]) && (0.0..=1.0).contains(&r[7]));
                if (80..=82).contains(&k) {
                    continue;
                }
                assert!((y - hf.sample(x, z)).abs() < 1e-3, "kind {k} floats at ({x},{z})");
                assert!(y >= 0.04, "kind {} in water at ({x},{z}) y={y}", names[k]);
            }
            for (k, what) in [(4, "palms"), (96, "shells"), (99, "beach grass"), (32, "daisies"), (80, "reeds"), (81, "lily pads"), (5, "willows"), (64, "boulders"), (2, "pines"), (18, "ferns"), (48, "mushrooms")] {
                assert!(per_kind[k] > 0, "seed {seed}: no {what}");
            }
        }
    }

    /// Dev aid: `cargo test -p sim_world preview -- --ignored --nocapture` writes `shots/voxel/r1/map_seedN.txt` (column heights).
    #[test]
    #[ignore = "writes a text height map of the voxel world"]
    fn preview() {
        let seed = std::env::var("SEED").ok().and_then(|s| s.parse().ok()).unwrap_or(1u32);
        let b = shared_built(seed);
        let mut counts: HashMap<u16, usize> = HashMap::new();
        for &v in &b.world.blocks {
            *counts.entry(v).or_insert(0) += 1;
        }
        let mut c: Vec<_> = counts.into_iter().collect();
        c.sort();
        eprintln!("seed {seed}: trees {}, decor {}, caves {:?}, cottages {:?}", b.tree_count, b.decor.len() / 8, b.caves, b.cottages);
        for (id, n) in c {
            eprintln!("  {:>14}: {n}", blocks::def(id).name);
        }
    }
}
