import { defineConfig } from 'vite';

/**
 * Glimmerwick web client build config.
 *
 * Notes
 * - Port 5173 is a contract (tools + .claude/launch.json depend on it) -> strictPort.
 * - `optimizeDeps.include` pre-bundles EVERY runtime dependency at server start. Without it Vite discovers
 *   deps lazily, re-optimises mid-session and force-reloads the page, which breaks headless shots.
 * - The wasm pkg (src/wasm/pkg/**) is generated by tools/build-wasm.ps1 and is absent until the first build;
 *   the engine reaches it through `import.meta.glob`, so a missing pkg is not a build error.
 */
export default defineConfig({
  server: {
    host: '127.0.0.1',
    port: 5173,
    strictPort: true,
    // The dev server must never be a security hole on a kid's laptop: loopback only, no CORS wildcard.
    cors: false,
    headers: { 'Cache-Control': 'no-store' },
    watch: { ignored: ['**/node_modules/**', '**/.git/**', '**/target/**'] },
  },
  preview: { host: '127.0.0.1', port: 5173, strictPort: true },
  build: {
    target: 'es2022',
    sourcemap: true,
    chunkSizeWarningLimit: 2500,
  },
  optimizeDeps: {
    include: [
      'three',
      'three/addons/lights/SunLight.js',
      'three/addons/utils/BufferGeometryUtils.js',
      'postprocessing',
      'three-mesh-bvh',
      'lil-gui',
      'stats-gl',
      'tone',
    ],
  },
});
